---
title: "Examples in 3D"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Examples in 3D}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  fig.asp=0.4,
  fig.width=8
)
```

This vignette contains a number of examples on how to use `clugenr` in 3D. Each
example must be preceded with:

```{r setup, message=FALSE, warning=FALSE}
library(clugenr)    # The clugenr library
library(plotly)     # Required for plotting
options(rgl.useNULL = TRUE)  # Create RGL plots in systems without displays (CI)
library(rgl)
setupKnitr(autoprint = TRUE) # Render RGL plots directly on generated page

# Load functions for plotting examples
source("plot_examples.R", local = knitr::knit_global())

# Keep examples reproducible in newer R versions 
RNGversion("3.6.0") 
```

## Manipulating the direction of cluster-supporting lines

### Using the `direction` parameter

```{r}
scene <- list(xaxis = list(range = list(-12, 27), dtick = 10),
              yaxis = list(range = list(-17, 22), dtick = 10),
              zaxis = list(range = list(-22, 22), dtick = 10),
              aspectmode = "cube")
seed <- 123
```

```{r}
set.seed(seed)
e40 <- clugen(3, 4, 500, c(1, 0, 0), 0, c(10, 10, 10), 15, 1.5, 0.5)
set.seed(seed)
e41 <- clugen(3, 4, 500, c(1, 1, 1), 0, c(10, 10, 10), 15, 1.5, 0.5)
set.seed(seed)
e42 <- clugen(3, 4, 500, c(0, 0, 1), 0, c(10, 10, 10), 15, 1.5, 0.5)
```

```{r}
plot_examples_3d(list(e = e40, t = "e40: direction = [1, 0, 0]"),
                 list(e = e41, t = "e41: direction = [1, 1, 1]"),
                 list(e = e42, t = "e42: direction = [0, 0, 1]"))
```

